#!/usr/bin/env sh
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
TEMPLATE="$ROOT/conf/nginx.conf.template"
OUTPUT_DIR="$ROOT/build"
OUTPUT="$OUTPUT_DIR/nginx.conf"
RUNTIME_CONFIG="$OUTPUT_DIR/runtime_config.lua"
ENV_FILE_VALUE="${ENV_FILE:-$ROOT/.env}"

load_env_file() {
  file="$1"
  [ -f "$file" ] || return 0
  set -a
  # shellcheck disable=SC1090
  . "$file"
  set +a
}

load_env_file "$ENV_FILE_VALUE"

BACKEND_UPSTREAMS_VALUE="${BACKEND_UPSTREAMS:-${BACKEND_UPSTREAM:-}}"
[ -n "$BACKEND_UPSTREAMS_VALUE" ] || {
  echo "BACKEND_UPSTREAMS or BACKEND_UPSTREAM is required" >&2
  exit 1
}

GATEWAY_BIND_VALUE="${GATEWAY_BIND:-0.0.0.0:8080}"
PROXY_CONNECT_TIMEOUT_VALUE="${PROXY_CONNECT_TIMEOUT:-3s}"
PROXY_READ_TIMEOUT_VALUE="${PROXY_READ_TIMEOUT:-30s}"
PROXY_SEND_TIMEOUT_VALUE="${PROXY_SEND_TIMEOUT:-30s}"
DNS_RESOLVER_VALUE="${DNS_RESOLVER:-127.0.0.11 ipv6=off valid=10s}"
LB_STRATEGY_VALUE="${LB_STRATEGY:-round_robin}"
SLOW_START_WINDOW_VALUE="${SLOW_START_WINDOW:-0}"
CONSISTENT_HASH_KEY_VALUE="${CONSISTENT_HASH_KEY:-remote_addr}"
CONSISTENT_HASH_HEADER_VALUE="${CONSISTENT_HASH_HEADER:-X-Request-ID}"
STICKY_LEARN_ENABLED_VALUE="${STICKY_LEARN_ENABLED:-false}"
STICKY_LEARN_COOKIES_VALUE="${STICKY_LEARN_COOKIES:-JSESSIONID,PHPSESSID}"
STICKY_LEARN_TTL_VALUE="${STICKY_LEARN_TTL:-3600}"
SESSION_STICKY_VALUE="${SESSION_STICKY:-true}"
SESSION_STICKY_MODE_VALUE="${SESSION_STICKY_MODE:-cookie}"
SESSION_COOKIE_NAME_VALUE="${SESSION_COOKIE_NAME:-OPENRESTY_LB_ROUTE}"
SESSION_HEADER_NAME_VALUE="${SESSION_HEADER_NAME:-X-Session-ID}"
SESSION_TTL_VALUE="${SESSION_TTL:-3600s}"
HEALTH_CHECK_ENABLED_VALUE="${HEALTH_CHECK_ENABLED:-true}"
HEALTH_CHECK_INTERVAL_VALUE="${HEALTH_CHECK_INTERVAL:-5s}"
HEALTH_CHECK_PATH_VALUE="${HEALTH_CHECK_PATH:-/healthz}"
HEALTH_CHECK_TIMEOUT_VALUE="${HEALTH_CHECK_TIMEOUT:-2s}"
HEALTH_CHECK_FAILS_VALUE="${HEALTH_CHECK_FAILS:-3}"
HEALTH_CHECK_PASSES_VALUE="${HEALTH_CHECK_PASSES:-2}"
HEALTH_CHECK_STATUS_CODES_VALUE="${HEALTH_CHECK_STATUS_CODES:-}"
HEALTH_CHECK_BODY_MATCH_VALUE="${HEALTH_CHECK_BODY_MATCH:-}"
HEALTH_CHECK_BODY_MATCH_NEGATE_VALUE="${HEALTH_CHECK_BODY_MATCH_NEGATE:-false}"
HEALTH_CHECK_HEADER_NAME_VALUE="${HEALTH_CHECK_HEADER_NAME:-}"
HEALTH_CHECK_HEADER_MATCH_VALUE="${HEALTH_CHECK_HEADER_MATCH:-}"
HEALTH_CHECK_MANDATORY_VALUE="${HEALTH_CHECK_MANDATORY:-false}"
API_GATEWAY_SECRET_VALUE="${API_GATEWAY_SECRET:-}"

[ -n "$API_GATEWAY_SECRET_VALUE" ] || {
  echo "API_GATEWAY_SECRET is required" >&2
  exit 1
}

mkdir -p "$OUTPUT_DIR" "$ROOT/logs"

TLS_CONFIG=""
if [ -n "${TLS_CERT_FILE:-}" ] || [ -n "${TLS_KEY_FILE:-}" ]; then
  [ -n "${TLS_CERT_FILE:-}" ] && [ -n "${TLS_KEY_FILE:-}" ] || {
    echo "TLS_CERT_FILE and TLS_KEY_FILE must be set together" >&2
    exit 1
  }
  TLS_CONFIG="        ssl_certificate ${TLS_CERT_FILE};
        ssl_certificate_key ${TLS_KEY_FILE};"
fi

sed \
  -e "s#__GATEWAY_LISTEN__#$GATEWAY_BIND_VALUE#g" \
  -e "s#__PROXY_CONNECT_TIMEOUT__#$PROXY_CONNECT_TIMEOUT_VALUE#g" \
  -e "s#__PROXY_READ_TIMEOUT__#$PROXY_READ_TIMEOUT_VALUE#g" \
  -e "s#__PROXY_SEND_TIMEOUT__#$PROXY_SEND_TIMEOUT_VALUE#g" \
  -e "s#__DNS_RESOLVER__#$DNS_RESOLVER_VALUE#g" \
  "$TEMPLATE" > "$OUTPUT.tmp"

awk -v tls="$TLS_CONFIG" '{ if ($0 == "__TLS_CONFIG__") print tls; else print }' "$OUTPUT.tmp" > "$OUTPUT"
rm -f "$OUTPUT.tmp"

echo "rendered $OUTPUT"

lua_quote() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

{
  echo "return {"
  echo "  BACKEND_UPSTREAMS = \"$(lua_quote "$BACKEND_UPSTREAMS_VALUE")\","
  echo "  BACKEND_UPSTREAM = \"$(lua_quote "$BACKEND_UPSTREAMS_VALUE")\","
  echo "  LB_STRATEGY = \"$(lua_quote "$LB_STRATEGY_VALUE")\","
  echo "  SLOW_START_WINDOW = \"$(lua_quote "$SLOW_START_WINDOW_VALUE")\","
  echo "  CONSISTENT_HASH_KEY = \"$(lua_quote "$CONSISTENT_HASH_KEY_VALUE")\","
  echo "  CONSISTENT_HASH_HEADER = \"$(lua_quote "$CONSISTENT_HASH_HEADER_VALUE")\","
  echo "  STICKY_LEARN_ENABLED = \"$(lua_quote "$STICKY_LEARN_ENABLED_VALUE")\","
  echo "  STICKY_LEARN_COOKIES = \"$(lua_quote "$STICKY_LEARN_COOKIES_VALUE")\","
  echo "  STICKY_LEARN_TTL = \"$(lua_quote "$STICKY_LEARN_TTL_VALUE")\","
  echo "  SESSION_STICKY = \"$(lua_quote "$SESSION_STICKY_VALUE")\","
  echo "  SESSION_STICKY_MODE = \"$(lua_quote "$SESSION_STICKY_MODE_VALUE")\","
  echo "  SESSION_COOKIE_NAME = \"$(lua_quote "$SESSION_COOKIE_NAME_VALUE")\","
  echo "  SESSION_HEADER_NAME = \"$(lua_quote "$SESSION_HEADER_NAME_VALUE")\","
  echo "  SESSION_TTL = \"$(lua_quote "$SESSION_TTL_VALUE")\","
  echo "  HEALTH_CHECK_ENABLED = \"$(lua_quote "$HEALTH_CHECK_ENABLED_VALUE")\","
  echo "  HEALTH_CHECK_INTERVAL = \"$(lua_quote "$HEALTH_CHECK_INTERVAL_VALUE")\","
  echo "  HEALTH_CHECK_PATH = \"$(lua_quote "$HEALTH_CHECK_PATH_VALUE")\","
  echo "  HEALTH_CHECK_TIMEOUT = \"$(lua_quote "$HEALTH_CHECK_TIMEOUT_VALUE")\","
  echo "  HEALTH_CHECK_FAILS = \"$(lua_quote "$HEALTH_CHECK_FAILS_VALUE")\","
  echo "  HEALTH_CHECK_PASSES = \"$(lua_quote "$HEALTH_CHECK_PASSES_VALUE")\","
  echo "  HEALTH_CHECK_STATUS_CODES = \"$(lua_quote "$HEALTH_CHECK_STATUS_CODES_VALUE")\","
  echo "  HEALTH_CHECK_BODY_MATCH = \"$(lua_quote "$HEALTH_CHECK_BODY_MATCH_VALUE")\","
  echo "  HEALTH_CHECK_BODY_MATCH_NEGATE = \"$(lua_quote "$HEALTH_CHECK_BODY_MATCH_NEGATE_VALUE")\","
  echo "  HEALTH_CHECK_HEADER_NAME = \"$(lua_quote "$HEALTH_CHECK_HEADER_NAME_VALUE")\","
  echo "  HEALTH_CHECK_HEADER_MATCH = \"$(lua_quote "$HEALTH_CHECK_HEADER_MATCH_VALUE")\","
  echo "  HEALTH_CHECK_MANDATORY = \"$(lua_quote "$HEALTH_CHECK_MANDATORY_VALUE")\","
  echo "  API_GATEWAY_SECRET = \"$(lua_quote "$API_GATEWAY_SECRET_VALUE")\","
  echo "  DNS_RESOLVER = \"$(lua_quote "$DNS_RESOLVER_VALUE")\","
  echo "}"
} > "$RUNTIME_CONFIG"

echo "rendered $RUNTIME_CONFIG"
